[package]
name = "grpc-masterkey-authorizer"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.1"
tokio = { version = "1.39.2", features = ["full"] }
prost = "0.13.1"
tonic-reflection = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
